### ISSUE TITLE
Tracking issue for Silk.NET documentation

### ISSUE THREAD

**Issue by Perksey** [Ultz/docs.ultz.co.uk#1]
- [ ] Windowing guide - *unclaimed*
- [ ] Input guide - @Deecellar
- [ ] OpenGL Tutorials - *unclaimed* 
- [ ] Advanced: AOT Guide - @HurricanKai

**Comment by Perksey** [comment]
@HurricanKai did you want to take the AOT guide?

**Comment by HurricanKai** [comment]
Yes, absolutely

**Comment by Perksey** [comment]
@Deecellar can you just give us the thumbs up on whether you're still good to work on the input guide.
